number of scholars to nominate added to model and showing in UI
OpenCLTBrigade/cmpd-holiday-gift pull request #119
Opened 2017-12-11 18:44 UTC by dallen72

2017-12-13 00:57 UTC, AndrewNatoli requested changes

2017-12-13 00:57 UTC, AndrewNatoli commented on server/models/household.js
> +    numNominates: {
Hey @dallen72, would you be able to change this field to `children_count`?

2017-12-13 00:57 UTC, AndrewNatoli commented on react-ui/src/app/dashboard/household/components/form/head-of-household.js
> +                    label="Number of Children to Nominate"
@dallen72 Could you change this label to "Number of children nominated?" (Minus the question mark)

Unless @Jillzey would prefer _another_ label?

2017-12-23 15:09 UTC, dallen72 commented
I forgot to say, I made the requested changes a few days ago.

2018-03-02 20:31 UTC, closed without merging